const NOTIFICATION_EVENTS = {
  // Attendance
  ATTENDANCE_CHECK_IN: "ATTENDANCE_CHECK_IN",
  ATTENDANCE_LATE: "ATTENDANCE_LATE",
  ATTENDANCE_CHECK_OUT: "ATTENDANCE_CHECK_OUT",

  // Leave
  LEAVE_APPLIED: "LEAVE_APPLIED",
  LEAVE_APPROVAL_PENDING: "LEAVE_APPROVAL_PENDING",
  LEAVE_APPROVED: "LEAVE_APPROVED",
  LEAVE_REJECTED: "LEAVE_REJECTED",

  // Payroll
  PAYSLIP_GENERATED: "PAYSLIP_GENERATED",
  SALARY_PROCESSED: "SALARY_PROCESSED",

  // Project
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_APPROVAL_PENDING: "PROJECT_APPROVAL_PENDING",
  PROJECT_APPROVED: "PROJECT_APPROVED",
  PROJECT_REJECTED: "PROJECT_REJECTED",

  // Task
  TASK_CREATED: "TASK_CREATED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_APPROVAL_PENDING: "TASK_APPROVAL_PENDING",
  TASK_APPROVED: "TASK_APPROVED",
  TASK_REJECTED: "TASK_REJECTED",
  TASK_STATUS_UPDATED: "TASK_STATUS_UPDATED",

  // Meeting
  MEETING_SCHEDULED: "MEETING_SCHEDULED",
  MEETING_UPDATED: "MEETING_UPDATED",
  MEETING_CANCELLED: "MEETING_CANCELLED",
};

export { NOTIFICATION_EVENTS };
